
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: delivery-platform
resources:
  #list of all the resource files in this directory
  - secrets.yaml

  #list of all the component folders
  - fastapi/
  - confluent-stack/
  - postgres/
  - akhq/ 
  - consumers/
  - base/
  - frontend/
  