
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: delivery-platform
resources:
  #list of all the resource files in this directory
  - secrets.yaml

  #list of all the component folders
  - base/
  - postgres/
  - kafka/
  - zookeeper/
  - schema-registry/
  - akhq/ 
  - fastapi/
  - consumers/
  - frontend/

  