#the main services that define the containers
services:
  #kafka all-in-one container
  fast-data-dev:
    image: lensesio/fast-data-dev:latest
    container_name: kafka-dev-box
    ports:
      - "9092:9092"    # kafka broker
      - "8081:8081"    # schema registry
      - "8082:8082"    # kafka connect
      - "8083:8083"    # kafka connect
      - "3030:3030"    # lenses ui
    environment:
      #hostname
      ADV_HOST: fast-data-dev  
      #access as root user      
      RUN_AS_USER: "root" 
      #allows topic recreation            
      TOPIC_RECREATE: "1"  
    #check if the service is healthy by pinging the schema registry endpoint           
    healthcheck:
      test: ["CMD", "curl", "-f", "http://fast-data-dev:8081"]
      #check every 20 seconds if the service is healthy
      interval: 20s
      #give it 10 seconds to respond
      timeout: 10s
      retries: 5
      start_period: 180s

  backend_consumer:
    #build the image using the Dockerfile in the current directory
    build: 
      context: .
      dockerfile: backend/Dockerfile
    
    #restart the container only if it stops unexpectedly
    restart: unless-stopped
    #make sure the consumer starts only after the database and kafka are healthy
    depends_on:
      postgres:
        condition: service_healthy
      fast-data-dev:
        condition: service_healthy
    env_file:
      - ./backend/.env.docker 
    #map the current directory to /usr/src/app in the container
    volumes:
      - ./:/usr/src/app
    #set the PYTHONUNBUFFERED environment variable to ensure real-time logging
    environment:
      PYTHONUNBUFFERED: 1
      PYTHONPATH: /usr/src/app:/usr/src/app/backend
    #run the consumer script
    command: python -m src.kafka.backend_consumer
    deploy:
      mode: replicated
      #make 2 replicas of the backend consumer for load balancing
      replicas: 2
  


  ml_service:
    build:
      context: .
      dockerfile: backend/Dockerfile 
    restart: unless-stopped
    depends_on:
      fast-data-dev:
        condition: service_healthy
    env_file:
      - ./backend/.env.docker
   
    volumes:
      - ./:/usr/src/app
    environment:
      PYTHONUNBUFFERED: 1
      PYTHONPATH: /usr/src/app:/usr/src/app/backend

    command: python -m src.kafka.ml_consumer
    deploy:
      mode: replicated
      replicas: 3


  akhq:
    image: tchiotludo/akhq:latest
    container_name: akhq
    ports:
      - "8080:8080"
    environment:
    #set the AKHQ CONFIGURATION to connect to the Kafka broker and schema registry
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            docker-kafka-cluster:
              properties:
                bootstrap.servers: "fast-data-dev:9092" 
              schema-registry:
                url: "http://fast-data-dev:8081"     
    depends_on:
      fast-data-dev:
        condition: service_healthy
      

  src:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: app
    depends_on:
      postgres:
        condition: service_healthy
      fast-data-dev:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - ./:/usr/src/app
    env_file:
      - ./backend/.env.docker
    environment:
      PYTHONPATH: /usr/src/app/backend:/usr/src/app

    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload

    

  postgres:
    image: postgres:16
    ports:
      - "5432:5432"
    #restart the container always if it stops 
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    env_file:
      - ./backend/.env.docker
    #check if the service is started and healthy by using pg_isready command
    healthcheck: 
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
    #this ensures that all the database data is saved persistently, even if the container is removed.
    volumes:
      - postgres_data:/var/lib/postgresql/data
   
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      #pass the Google API key build argument to the Dockerfile 
      args:
        - VITE_GOOGLE_API_KEY=${VITE_GOOGLE_API_KEY}
    image: jony6273/smart-delivery-frontend:main
    container_name: frontend
    ports:
      - "3000:80" 
    
    env_file:
        - ./frontend/.env
        
#define a named volume for persistent Postgres data storage
volumes:
  postgres_data: