# This file defines the deployment for the FastAPI application in the Kubernetes cluster.


#the version of the kubernetes api to use for this object
apiVersion: apps/v1
kind: Deployment
#the information that identifies the object, like its name and namespace.
metadata:
  name: fastapi-deployment
spec:
  #one copy of the pod should be running at all times
  replicas: 1
  #this section defines how to identify the pods that belong to this deployment.
  selector:
    matchLabels:
      app: fastapi

#this section defines the template for the pods that will be created by this deployment.
  template:
    metadata:
      labels:
        app: fastapi
    #this section defines the specification for the pod.
    spec:
      #init container to run alembic migrations before starting the main application container
      initContainers:
      - name: wait-for-postgres
        image: busybox:1.36
        command: ['sh', '-c', 'until nc -z postgres-service 5432; do echo waiting for postgres; sleep 2; done;']
      
      - name: wait-for-kafka
        image: busybox:1.36
        command: ['sh', '-c', 'until nc -z kafka-service 9092; do echo waiting for kafka; sleep 2; done;']

      - name: db-migration
        image: jony6273/smart-delivery:main
        imagePullPolicy: Always
        command: ["alembic", "upgrade", "head"]

        envFrom:
        - configMapRef:
            name: app-config

        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: POSTGRES_PASSWORD
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: DATABASE_URL

      #this section defines the containers that will run in the pod.
      containers:
        - name: fastapi
          image: jony6273/smart-delivery:main
          imagePullPolicy: Always
          command: ["uvicorn","src.main:app", "--host", "0.0.0.0", "--port", "8000"]
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: app-config
          #define resource requests and limits for the container
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "100m"
              memory: "128Mi"
          
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_PASSWORD
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: SECRET_KEY
            - name: GOOGLE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: GOOGLE_API_KEY
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DATABASE_URL
          #define a liveness probe to check if the application is running and healthy 
          livenessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3