#this file defines the service for the fastapi application in the kubernetes cluster.
apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
spec:
  #this type ensures balance between the containers load and external access
  #and checks the health of the pods
  type: LoadBalancer 
  #this section defines the port mapping rules for the Service.
  ports:
    # the port that the Service itself will expose on its internal IP
    - port: 8000
      targetPort: 8000
  selector:
    app: fastapi