#this file defines the service for the kafka application in the kubernetes cluster.

apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: delivery-platform
spec:
  ports:
    - name: plaintext
      #other applications will connect to the Kafka broker on this port
      port: 9092
  selector:
    app: kafka