apiVersion: apps/v1
kind: Deployment
metadata:
  name: akhq-deployment

spec:
  replicas: 1
  selector:
    matchLabels:
      app: akhq

  template:
  
    metadata:
      labels:
        app: akhq

    spec:
      containers:
      - name: akhq
        image: tchiotludo/akhq:latest
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
        env:
        # AKHQ configuration to connect to Kafka and Schema Registry services
        - name: AKHQ_CONFIGURATION
          value: |
            akhq:
              connections:
                kubernetes-kafka-cluster:
                  properties:
                    bootstrap.servers: "kafka-service:9092"
                  schema-registry:
                    url: "http://schema-registry-service:8081"