apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-consumer-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-consumer
  template:
    metadata:
      labels:
        app: backend-consumer
    spec:
      initContainers:
        - name: init-kafka-topics
          image: jony6273/smart-delivery:main
          imagePullPolicy: Always
          #create necessary kafka topics before starting the consumer
          command: ["python", "-c", "from src.kafka.admin import create_topic_init; create_topic_init()"]
          envFrom:
            - configMapRef:
                name: app-config
      containers:
        - name: backend-consumer
          image: jony6273/smart-delivery:main
          imagePullPolicy: Always
          #run the backend_consumer module to start consuming messages
          command: ["python", "-m", "src.kafka.backend_consumer"]
          envFrom:
            - configMapRef:
                name: app-config
                
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_PASSWORD
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DATABASE_URL
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "50m"
              memory: "64Mi"