apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config 
data:

  KAFKA_BROKER_ID: "1"
  #zookeeper connection 
  KAFKA_ZOOKEEPER_CONNECT: "zookeeper-service:2181"
    #security protocol map so that listeners can communicate
  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT"
  #the port that the broker will use to communicate with other brokers
  KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
  #kafka listeners properties
  KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092"
  #kafka advertised listeners properties
  KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka-service:9092"
  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"