# FastAPI Deployment Configuration
# This file defines the deployment for the FastAPI application in the Kubernetes cluster.

#the version of the kubernetes api to use for this object
apiVersion: apps/v1
kind: Deployment
#the information that identifies the object, like its name and namespace.
metadata:
  name: fastapi-deployment
  namespace: delivery-platform
#describes the desired state for the Deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
        - name: fastapi
          image: smart-delivery-src:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: app-config
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_PASSWORD
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: SECRET_KEY
            - name: GOOGLE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: GOOGLE_API_KEY