apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: delivery-platform

resources:
  - schema_registry-service.yaml 
  - schema_registry-deployment.yaml
  - schema-registry-config.yaml
  