apiVersion: apps/v1
kind: Deployment
metadata:
  name: schema-registry-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: schema-registry
  template:
    metadata:
      labels:
        app: schema-registry
    
    spec:
      initContainers:
       
        - name: wait-for-cluster
          image: busybox:1.36
          command: ['sh', '-c', 'until nc -z zookeeper-service 2181 &&
                    nc -z kafka-service 9092; do echo waiting for cluster; sleep 2; done;']
      containers:
        - name: schema-registry
          image: confluentinc/cp-schema-registry:7.6.1
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: schema-registry-config
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"