"""add lat long columns

Revision ID: a4ecb7784221
Revises: 934a9b7460b8
Create Date: 2025-12-25 16:12:18.221297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4ecb7784221'
down_revision: Union[str, None] = '934a9b7460b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deliveries', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('deliveries', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deliveries', 'longitude')
    op.drop_column('deliveries', 'latitude')
    # ### end Alembic commands ###
