"""Add predicted_eta_minutes to deliveries table

Revision ID: e1ee85e0b944
Revises: 313fefd02c0c
Create Date: 2025-09-27 14:46:15.094775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e1ee85e0b944'
down_revision: Union[str, None] = '313fefd02c0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.add_column('deliveries', sa.Column('predicted_eta_minutes', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('time_of_created', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_column('users', 'created_at')
    op.add_column('deliveries', sa.Column('time_of_created', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_column('deliveries', 'predicted_eta_minutes')
    op.drop_column('deliveries', 'created_at')
    # ### end Alembic commands ###
