apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  
data:
  #postgresql configuration
  POSTGRES_DB: "deliveries_database"
  POSTGRES_USER: "postgres"
  POSTGRES_HOSTNAME: "postgres-service"
  POSTGRES_PORT: "5432"

  #kafka and schema registry configuration
  KAFKA_BOOTSTRAP_SERVERS: "kafka-service:9092"
  SCHEMA_REGISTRY_URL: "http://schema-registry-service:8081"
  KAFKA_TOPIC_CALCULATE_ROUTE: "calculate_route"

  #jwt configuration
  ALGORITHM: "HS256"
  ACCESS_TOKEN_EXPIRE_MINUTES: "30"