name: build and deploy code

on: [push, pull_request]
    
jobs:
  build:
    environment:
      name: testing
    env:
      POSTGRES_PORT: 5432
      POSTGRES_HOSTNAME: localhost
      POSTGRES_DB: ${{secrets.POSTGRES_DB}}
      POSTGRES_USER: ${{secrets.POSTGRES_USER}}
      POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
      SECRET_KEY: ${{secrets.SECRET_KEY}}
      ALGORITHM: ${{secrets.ALGORITHM}}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${{secrets.ACCESS_TOKEN_EXPIRE_MINUTES}}
      GOOGLE_API_KEY: ${{secrets.GOOGLE_API_KEY}}
      KAFKA_BOOTSTRAP_SERVERS: localhost:9092
      KAFKA_TOPIC_CALCULATE_ROUTE: ${{secrets.KAFKA_TOPIC_CALCULATE_ROUTE}}
      KAFKA_CONSUMER_GROUP: ${{secrets.KAFKA_CONSUMER_GROUP}}
      SCHEMA_REGISTRY_URL: http://localhost:8081

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}} 
          POSTGRES_DB: ${{secrets.POSTGRES_DB}}_test
        ports:
          - 5432:5432
        #set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      kafka-stack:
        image: lensesio/fast-data-dev:latest
        ports:
          - 9092:9092  # Kafka Broker
          - 8081:8081  # Schema Registry
        env:
          ADV_HOST: localhost 
          RUN_AS_USER: "root"
          TOPIC_RECREATE: "1"

        options: >-
          --health-cmd "curl -f -s http://localhost:8081/subjects"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 15 # נותן לזה קצת יותר זמן לעלות
          --health-start-period 30s # נותן 30 שניות ראשוניות להתנעה

    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v5
        with: 
          lfs: true

      - name: Lint dockerfile
        run: docker run --rm -v "$(pwd):/work" -w /work hadolint/hadolint hadolint Dockerfile

      - name: install python version 3.12.8
        uses: actions/setup-python@v6 
        with:
          python-version: '3.12.8'

      - name: update pip
        run: python -m pip install --upgrade pip

      - name: install all dependencies
        run: pip install -r requirements.txt

      - name: Run Tests with Pytest
        timeout-minutes: 4
        run: |
          echo "all services are healthy running tests."
          pytest

      - name: Debug Container Logs
        if: failure()
        run: |
          echo "docker container status"
          docker ps -a
          
          echo "kafka Stack (fast-data-dev) container logs "
          docker logs $(docker ps -a --filter "ancestor=lensesio/fast-data-dev" --format "{{.ID}}") || echo "kafka Stack logs not found."

          echo "postgres container logs"
          docker logs $(docker ps -a --filter "ancestor=postgres" --format "{{.ID}}") || echo "Postgres logs not found."
          
          
      - name: Extract Docker image metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ vars.DOCKER_USERNAME }}/smart-delivery

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and load Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          load: true
          push: false
          tags: ${{ steps.meta.outputs.tags }}
       
      - name: Run smoke test
        run: |
          docker run -d --name smart-delivery-test -p 8000:8000 ${{ steps.meta.outputs.tags }}
          sleep 15
          curl -f http://localhost:8000/docs || exit 1

      - name: Push Docker Image to Docker Hub
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: docker push ${{ steps.meta.outputs.tags }}